# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zuruapp', '0002_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
    ]
